version: '3.1'

services:
  java-biblioteka-mysql:
    image: mysql:8
    volumes:
      - "./db-data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
    ports:
      - 3306:3306

  java-biblioteka-phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - java-biblioteka-mysql
